apiVersion: v1
kind: Service
metadata:
  labels:
    app: soluciones-postgres
  name: soluciones-postgres
  namespace: default
spec:
  ports:
  - name: primary
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: soluciones-postgres