apiVersion: v1
kind: PersistentVolume
metadata:
  name: soluciones-disco
  labels:
    app: soluciones-disco
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pg-data
    fsType: ext4